"""initial schema

Revision ID: 211cc6588dc9
Revises: 
Create Date: 2026-03-10 07:47:49.788880
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


revision: str = '211cc6588dc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_album',
    sa.Column('album_id', sa.String(length=64), nullable=False, comment='Spotify album ID'),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('album_type', sa.String(length=32), nullable=True),
    sa.Column('release_date', sa.String(length=16), nullable=True, comment='YYYY or YYYY-MM-DD'),
    sa.Column('release_year', sa.SmallInteger(), nullable=True),
    sa.Column('total_tracks', sa.SmallInteger(), nullable=True),
    sa.Column('image_url_large', sa.Text(), nullable=True),
    sa.Column('image_url_medium', sa.Text(), nullable=True),
    sa.Column('image_url_small', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_index(op.f('ix_dim_album_name'), 'dim_album', ['name'], unique=False)
    op.create_index(op.f('ix_dim_album_release_year'), 'dim_album', ['release_year'], unique=False)
    op.create_table('dim_artist',
    sa.Column('artist_id', sa.String(length=64), nullable=False, comment='Spotify artist ID'),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=True, comment='Genre list from Spotify'),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.SmallInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('has_image', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_index(op.f('ix_dim_artist_name'), 'dim_artist', ['name'], unique=False)
    op.create_table('dim_genre',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_index(op.f('ix_dim_genre_name'), 'dim_genre', ['name'], unique=True)
    op.create_table('dim_mood',
    sa.Column('mood_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quadrant', sa.String(length=4), nullable=False, comment='Q1-Q4'),
    sa.Column('quadrant_name', sa.String(length=64), nullable=False),
    sa.Column('mood_label', sa.String(length=64), nullable=True),
    sa.Column('valence_center', sa.Float(), nullable=True),
    sa.Column('energy_center', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('mood_id')
    )
    op.create_index(op.f('ix_dim_mood_mood_label'), 'dim_mood', ['mood_label'], unique=True)
    op.create_table('dim_user',
    sa.Column('user_id', sa.String(length=32), nullable=False, comment='Hex UID from auth'),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('avatar_emoji', sa.String(length=8), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('password_salt', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_attempts', sa.SmallInteger(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_dim_user_username'), 'dim_user', ['username'], unique=True)
    op.create_table('bridge_artist_genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.String(length=64), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['dim_artist.artist_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['dim_genre.genre_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'genre_id', name='uq_artist_genre')
    )
    op.create_index(op.f('ix_bridge_artist_genre_artist_id'), 'bridge_artist_genre', ['artist_id'], unique=False)
    op.create_index(op.f('ix_bridge_artist_genre_genre_id'), 'bridge_artist_genre', ['genre_id'], unique=False)
    op.create_table('dim_song',
    sa.Column('track_id', sa.String(length=64), nullable=False, comment='Spotify track ID'),
    sa.Column('track_name', sa.String(length=512), nullable=False),
    sa.Column('album_id', sa.String(length=64), nullable=True),
    sa.Column('primary_artist_id', sa.String(length=64), nullable=True),
    sa.Column('primary_artist_name', sa.String(length=512), nullable=True),
    sa.Column('isrc', sa.String(length=16), nullable=True),
    sa.Column('track_number', sa.SmallInteger(), nullable=True),
    sa.Column('disc_number', sa.SmallInteger(), nullable=True),
    sa.Column('popularity', sa.SmallInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('track_url', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('available_markets_count', sa.SmallInteger(), nullable=True),
    sa.Column('image_url_large', sa.Text(), nullable=True),
    sa.Column('image_url_medium', sa.Text(), nullable=True),
    sa.Column('image_url_small', sa.Text(), nullable=True),
    sa.Column('has_art', sa.Boolean(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('key', sa.SmallInteger(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('mode', sa.SmallInteger(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('time_signature', sa.SmallInteger(), nullable=True),
    sa.Column('has_audio_features', sa.Boolean(), nullable=True),
    sa.Column('lrclib_id', sa.BigInteger(), nullable=True),
    sa.Column('plain_lyrics', sa.Text(), nullable=True),
    sa.Column('synced_lyrics', sa.Text(), nullable=True),
    sa.Column('instrumental', sa.Boolean(), nullable=True),
    sa.Column('has_lyrics', sa.Boolean(), nullable=True),
    sa.Column('lyrics_cleaned', sa.Text(), nullable=True),
    sa.Column('color_hue', sa.Float(), nullable=True),
    sa.Column('color_saturation', sa.Float(), nullable=True),
    sa.Column('color_lightness', sa.Float(), nullable=True),
    sa.Column('color_hex', sa.String(length=8), nullable=True),
    sa.Column('sentiment_compound', sa.Float(), nullable=True),
    sa.Column('sentiment_positive', sa.Float(), nullable=True),
    sa.Column('sentiment_neutral', sa.Float(), nullable=True),
    sa.Column('sentiment_negative', sa.Float(), nullable=True),
    sa.Column('sentiment_category', sa.String(length=16), nullable=True),
    sa.Column('mood_score', sa.Float(), nullable=True),
    sa.Column('mood_quadrant', sa.String(length=4), nullable=True),
    sa.Column('mood_id', sa.Integer(), nullable=True),
    sa.Column('dance_score', sa.Float(), nullable=True),
    sa.Column('acoustic_score', sa.Float(), nullable=True),
    sa.Column('combined_positivity', sa.Float(), nullable=True),
    sa.Column('energy_level', sa.String(length=16), nullable=True),
    sa.Column('tempo_category', sa.String(length=16), nullable=True),
    sa.Column('has_mp3', sa.Boolean(), nullable=True),
    sa.Column('mp3_filename', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['dim_album.album_id'], ),
    sa.ForeignKeyConstraint(['mood_id'], ['dim_mood.mood_id'], ),
    sa.ForeignKeyConstraint(['primary_artist_id'], ['dim_artist.artist_id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_index(op.f('ix_dim_song_album_id'), 'dim_song', ['album_id'], unique=False)
    op.create_index(op.f('ix_dim_song_has_lyrics'), 'dim_song', ['has_lyrics'], unique=False)
    op.create_index(op.f('ix_dim_song_popularity'), 'dim_song', ['popularity'], unique=False)
    op.create_index(op.f('ix_dim_song_primary_artist_id'), 'dim_song', ['primary_artist_id'], unique=False)
    op.create_index(op.f('ix_dim_song_track_name'), 'dim_song', ['track_name'], unique=False)
    op.create_index('ix_song_color', 'dim_song', ['color_hex'], unique=False)
    op.create_index('ix_song_mood', 'dim_song', ['mood_quadrant'], unique=False)
    op.create_index('ix_song_valence_energy', 'dim_song', ['valence', 'energy'], unique=False)
    op.create_table('fact_follow',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('artist_id', sa.String(length=64), nullable=False),
    sa.Column('followed', sa.Boolean(), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['dim_artist.artist_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'artist_id', name='uq_user_artist_follow')
    )
    op.create_index(op.f('ix_fact_follow_artist_id'), 'fact_follow', ['artist_id'], unique=False)
    op.create_index(op.f('ix_fact_follow_user_id'), 'fact_follow', ['user_id'], unique=False)
    op.create_table('playlist',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_user_id'), 'playlist', ['user_id'], unique=False)
    op.create_table('bridge_song_artist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('artist_id', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['dim_artist.artist_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['dim_song.track_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'artist_id', name='uq_song_artist')
    )
    op.create_index(op.f('ix_bridge_song_artist_artist_id'), 'bridge_song_artist', ['artist_id'], unique=False)
    op.create_index(op.f('ix_bridge_song_artist_track_id'), 'bridge_song_artist', ['track_id'], unique=False)
    op.create_table('fact_like',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['dim_song.track_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', name='uq_user_song_like')
    )
    op.create_index(op.f('ix_fact_like_track_id'), 'fact_like', ['track_id'], unique=False)
    op.create_index(op.f('ix_fact_like_user_id'), 'fact_like', ['user_id'], unique=False)
    op.create_table('fact_listen',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('listened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='How long user actually listened'),
    sa.Column('source', sa.String(length=32), nullable=True, comment='search, recommend, playlist, radio, queue'),
    sa.ForeignKeyConstraint(['track_id'], ['dim_song.track_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_listen_listened_at'), 'fact_listen', ['listened_at'], unique=False)
    op.create_index(op.f('ix_fact_listen_track_id'), 'fact_listen', ['track_id'], unique=False)
    op.create_index(op.f('ix_fact_listen_user_id'), 'fact_listen', ['user_id'], unique=False)
    op.create_table('fact_playlist_song',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.String(length=16), nullable=False),
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['dim_song.track_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'track_id', name='uq_playlist_song')
    )
    op.create_index(op.f('ix_fact_playlist_song_playlist_id'), 'fact_playlist_song', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_fact_playlist_song_track_id'), 'fact_playlist_song', ['track_id'], unique=False)
    op.create_table('fact_recommendation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('rec_type', sa.String(length=32), nullable=False, comment='color, mood, lyrics, image, context, dna, radio'),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('rank_position', sa.SmallInteger(), nullable=True),
    sa.Column('query_params', sa.JSON(), nullable=True, comment='Input params that generated this rec'),
    sa.Column('was_played', sa.Boolean(), nullable=True),
    sa.Column('was_liked', sa.Boolean(), nullable=True),
    sa.Column('recommended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['dim_song.track_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_recommendation_recommended_at'), 'fact_recommendation', ['recommended_at'], unique=False)
    op.create_index(op.f('ix_fact_recommendation_track_id'), 'fact_recommendation', ['track_id'], unique=False)
    op.create_index(op.f('ix_fact_recommendation_user_id'), 'fact_recommendation', ['user_id'], unique=False)
    op.create_table('song_embedding',
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['dim_song.track_id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_embedding')
    op.drop_index(op.f('ix_fact_recommendation_user_id'), table_name='fact_recommendation')
    op.drop_index(op.f('ix_fact_recommendation_track_id'), table_name='fact_recommendation')
    op.drop_index(op.f('ix_fact_recommendation_recommended_at'), table_name='fact_recommendation')
    op.drop_table('fact_recommendation')
    op.drop_index(op.f('ix_fact_playlist_song_track_id'), table_name='fact_playlist_song')
    op.drop_index(op.f('ix_fact_playlist_song_playlist_id'), table_name='fact_playlist_song')
    op.drop_table('fact_playlist_song')
    op.drop_index(op.f('ix_fact_listen_user_id'), table_name='fact_listen')
    op.drop_index(op.f('ix_fact_listen_track_id'), table_name='fact_listen')
    op.drop_index(op.f('ix_fact_listen_listened_at'), table_name='fact_listen')
    op.drop_table('fact_listen')
    op.drop_index(op.f('ix_fact_like_user_id'), table_name='fact_like')
    op.drop_index(op.f('ix_fact_like_track_id'), table_name='fact_like')
    op.drop_table('fact_like')
    op.drop_index(op.f('ix_bridge_song_artist_track_id'), table_name='bridge_song_artist')
    op.drop_index(op.f('ix_bridge_song_artist_artist_id'), table_name='bridge_song_artist')
    op.drop_table('bridge_song_artist')
    op.drop_index(op.f('ix_playlist_user_id'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_index(op.f('ix_fact_follow_user_id'), table_name='fact_follow')
    op.drop_index(op.f('ix_fact_follow_artist_id'), table_name='fact_follow')
    op.drop_table('fact_follow')
    op.drop_index('ix_song_valence_energy', table_name='dim_song')
    op.drop_index('ix_song_mood', table_name='dim_song')
    op.drop_index('ix_song_color', table_name='dim_song')
    op.drop_index(op.f('ix_dim_song_track_name'), table_name='dim_song')
    op.drop_index(op.f('ix_dim_song_primary_artist_id'), table_name='dim_song')
    op.drop_index(op.f('ix_dim_song_popularity'), table_name='dim_song')
    op.drop_index(op.f('ix_dim_song_has_lyrics'), table_name='dim_song')
    op.drop_index(op.f('ix_dim_song_album_id'), table_name='dim_song')
    op.drop_table('dim_song')
    op.drop_index(op.f('ix_bridge_artist_genre_genre_id'), table_name='bridge_artist_genre')
    op.drop_index(op.f('ix_bridge_artist_genre_artist_id'), table_name='bridge_artist_genre')
    op.drop_table('bridge_artist_genre')
    op.drop_index(op.f('ix_dim_user_username'), table_name='dim_user')
    op.drop_table('dim_user')
    op.drop_index(op.f('ix_dim_mood_mood_label'), table_name='dim_mood')
    op.drop_table('dim_mood')
    op.drop_index(op.f('ix_dim_genre_name'), table_name='dim_genre')
    op.drop_table('dim_genre')
    op.drop_index(op.f('ix_dim_artist_name'), table_name='dim_artist')
    op.drop_table('dim_artist')
    op.drop_index(op.f('ix_dim_album_release_year'), table_name='dim_album')
    op.drop_index(op.f('ix_dim_album_name'), table_name='dim_album')
    op.drop_table('dim_album')
    # ### end Alembic commands ###
