"""fix mood_quadrant column size

Revision ID: c041fcfee2bf
Revises: 211cc6588dc9
Create Date: 2026-03-10 07:49:57.051748
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c041fcfee2bf'
down_revision: Union[str, None] = '211cc6588dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_mood', 'quadrant',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=32),
               comment='Q1-Q4 with label',
               existing_comment='Q1-Q4',
               existing_nullable=False)
    op.alter_column('dim_song', 'mood_quadrant',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_song', 'mood_quadrant',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.alter_column('dim_mood', 'quadrant',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=4),
               comment='Q1-Q4',
               existing_comment='Q1-Q4 with label',
               existing_nullable=False)
    # ### end Alembic commands ###
