"""add fact_search table

Revision ID: 00fa7d35b82e
Revises: c041fcfee2bf
Create Date: 2026-03-10 10:04:31.870511
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '00fa7d35b82e'
down_revision: Union[str, None] = 'c041fcfee2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_search',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True, comment='NULL for anonymous searches'),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True, comment='Number of results returned'),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fact_search_searched_at'), 'fact_search', ['searched_at'], unique=False)
    op.create_index(op.f('ix_fact_search_user_id'), 'fact_search', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_search_user_id'), table_name='fact_search')
    op.drop_index(op.f('ix_fact_search_searched_at'), table_name='fact_search')
    op.drop_table('fact_search')
    # ### end Alembic commands ###
