"""add_mp3_fields_play_history_preference_vector

Revision ID: 9c9733a7709f
Revises: 00fa7d35b82e
Create Date: 2026-03-10 12:59:59.502006
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '9c9733a7709f'
down_revision: Union[str, None] = '00fa7d35b82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_play_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('song_id', sa.String(length=64), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('play_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['dim_song.track_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_play_history', 'fact_play_history', ['user_id', 'played_at'], unique=False)
    op.create_index(op.f('ix_fact_play_history_song_id'), 'fact_play_history', ['song_id'], unique=False)
    op.create_index(op.f('ix_fact_play_history_user_id'), 'fact_play_history', ['user_id'], unique=False)
    op.add_column('dim_song', sa.Column('mp3_path', sa.Text(), nullable=True))
    op.add_column('dim_song', sa.Column('mp3_source', sa.String(length=32), nullable=True, comment='youtube_music | youtube_lyrics | youtube_mv | youtube_general'))
    op.add_column('dim_song', sa.Column('mp3_duration_s', sa.Integer(), nullable=True))
    op.add_column('dim_song', sa.Column('mp3_quality', sa.String(length=16), nullable=True, comment='clean | has_extra | low'))
    op.add_column('dim_song', sa.Column('youtube_music_id', sa.String(length=32), nullable=True))
    op.add_column('dim_song', sa.Column('youtube_id', sa.String(length=32), nullable=True))
    op.add_column('dim_user', sa.Column('preference_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_user', 'preference_vector')
    op.drop_column('dim_song', 'youtube_id')
    op.drop_column('dim_song', 'youtube_music_id')
    op.drop_column('dim_song', 'mp3_quality')
    op.drop_column('dim_song', 'mp3_duration_s')
    op.drop_column('dim_song', 'mp3_source')
    op.drop_column('dim_song', 'mp3_path')
    op.drop_index(op.f('ix_fact_play_history_user_id'), table_name='fact_play_history')
    op.drop_index(op.f('ix_fact_play_history_song_id'), table_name='fact_play_history')
    op.drop_index('idx_play_history', table_name='fact_play_history')
    op.drop_table('fact_play_history')
    # ### end Alembic commands ###
